platform :ios, '9.0'
use_frameworks!

target 'SquareMosaicLayout_Example' do
   
   pod 'SquareMosaicLayout', :path => '../'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
